on:
  push:
    branches:
      - main
    paths:
      - registration/**

jobs:
  test:
    name: Build And Test
    uses: ./.github/workflows/registration-build.yml
    secrets: inherit

  publish:
    needs: [test]
    name: Publish Registration Page
    uses: ./.github/workflows/registration-publish.yml
    secrets: inherit